package com.group5.rent_n_drive

data class Car(val id: Int, val name: String, val type: String, val imageUrl: String)

val cars = listOf(
    Car(1, "Honda Civic", "Compact", "https://www.honda.com/content/dam/honda/na/us/vehicles/cars/civic/2021/gallery/2021-civic-front-view-01.png"),
    Car(2, "Toyota Supra", "Sport", "https://www.toyota.com/content/dam/toyota/na/us/vehicles/supra/2021/gallery/2021-supra-front-view-01.png"),
    Car(3, "Audi A4", "Sedan", "https://www.audi.com/content/dam/gbp/images/models/a4/a4-sedan/a4-sedan-front-view-01.png"),
    Car(4, "BMW 3 Series", "Sedan", "https://www.bmw.com/content/dam/bmw/common/all-models/3-series/2021/navigation/320i-gran-turismo/2021-bmw-3-series-320i-gran-turismo-front-view-01.png"),
    Car(5, "Mercedes-Benz E-Class", "Sedan", "https://www.mercedes-benz.com/content/dam/mercedes-benz/passengercars/models/e-class/e-class-sedan/2021/navigation/e-class-sedan-front-view-01.png"),
    Car(6, "Tesla Model 3", "Sedan", "https://www.tesla.com/vehicles/model3/gallery/model3_std_frontview"),
    Car(7, "Chevrolet Impala", "Sedan", "https://www.chevrolet.com/content/dam/chevrolet/na/us/vehicles/cars/2021/impala/gallery/2021-impala-front-view-01.png"),
    Car(8, "Ford Mustang", "Sport", "https://www.ford.com/content/dam/ford/na/us/cars/mustang/2021/gallery/2021-mustang-front-view-01.png"),
    Car(9, "Dodge Charger", "Sedan", "https://www.dodge.com/content/dam/dodge/na/us/cars/charger/2021/gallery/2021-charger-front-view-01.png"),
    Car(10, "Hyundai Elantra", "Sedan", "https://www.hyundai.com/content/dam/hyundai/na/us/vehicles/cars/elantra/2021/gallery/2021-elantra-front-view-01.png"),
    Car(11, "Nissan Altima", "Sedan", "https://www.nissanusa.com/content/dam/nissan/na/us/vehicles/cars/altima/2021/gallery/2021-altima-front-view-01.png"),
    Car(12, "Subaru Outback", "SUV", "https://www.subaru.com/content/dam/subaru/na/us/vehicles/outback/2021/gallery/2021-outback-front-view-01.png"),
    Car(13, "Volkswagen Golf", "Compact", "https://www.volkswagen.com/content/dam/volkswagen/na/us/models/golf/golf-golf-r/2021/navigation/golf-golf-r-front-view-01.png"),
    Car(14, "Audi Q7", "SUV", "https://www.audi.com/content/dam/gbp/images/models/q7/q7-suv/q7-suv-front-view-01.png"),
    Car(15, "BMW X5", "SUV", "https://www.bmw.com/content/dam/bmw/common/all-models/x5/2021/navigation/x5-m-front-view-01.png"),
    Car(16, "Mercedes-Benz GLE", "SUV", "https://www.mercedes-benz.com/content/dam/mercedes-benz/passengercars/models/gle/gle-suv/2021/navigation/gle-suv-front-view-01.png"),
    Car(17, "Tesla Model X", "SUV", "https://www.tesla.com/vehicles/modelx/gallery/modelx_std_frontview"),
    Car(18, "Chevrolet Tahoe", "SUV", "https://www.chevrolet.com/content/dam/chevrolet/na/us/vehicles/cars/tahoe/2021/gallery/2021-tahoe-front-view-01.png"),
    Car(19, "Ford Explorer", "SUV", "https://www.ford.com/content/dam/ford/na/us/cars/explorer/2021/gallery/2021-explorer-front-view-01.png"),
    Car(20, "Dodge Durango", "SUV", "https://www.dodge.com/content/dam/dodge/na/us/cars/durango/2021/gallery/2021-durango-front-view-01.png"),
    Car(21, "Hyundai Santa Fe", "SUV", "https://www.hyundai.com/content/dam/hyundai/na/us/vehicles/cars/santa-fe/2021/gallery/2021-santa-fe-front-view-01.png"),
    Car(22, "Nissan Rogue", "SUV", "https://www.nissanusa.com/content/dam/nissan/na/us/vehicles/cars/rogue/2021/gallery/2021-rogue-front-view-01.png"),
    Car(23, "Subaru Crosstrek", "SUV", "https://www.subaru.com/content/dam/subaru/na/us/vehicles/crosstrek/2021/gallery/2021-crosstrek-front-view-01.png"),
    Car(24, "Volkswagen Tiguan", "SUV", "https://www.volkswagen.com/content/dam/volkswagen/na/us/models/tiguan/tiguan-suv/2021/navigation/tiguan-suv-front-view-01.png"),
    Car(25, "Audi Q5", "SUV", "https://www.audi.com/content/dam/gbp/images/models/q5/q5-suv/q5-suv-front-view-01.png"),
    Car(26, "BMW X3", "SUV", "https://www.bmw.com/content/dam/bmw/common/all-models/x3/2021/navigation/x3-m-front-view-01.png"),
    Car(27, "Mercedes-Benz GLA", "SUV", "https://www.mercedes-benz.com/content/dam/mercedes-benz/passengercars/models/gla/gla-suv/2021/navigation/gla-suv-front-view-01.png"),
    Car(28, "Tesla Model Y", "SUV", "https://www.tesla.com/vehicles/modely/gallery/modely_std_frontview"),
    Car(29, "Chevrolet Blazer", "SUV", "https://www.chevrolet.com/content/dam/chevrolet/na/us/vehicles/cars/blazer/2021/gallery/2021-blazer-front-view-01.png"),
    Car(30, "Ford Escape", "SUV", "https://www.ford.com/content/dam/ford/na/us/cars/escape/2021/gallery/2021-escape-front-view-01.png"),
    Car(31, "Dodge Journey", "SUV", "https://www.dodge.com/content/dam/dodge/na/us/cars/journey/2021/gallery/2021-journey-front-view-01.png"),
    Car(32, "Hyundai Kona", "SUV", "https://www.hyundai.com/content/dam/hyundai/na/us/vehicles/cars/kona/2021/gallery/2021-kona-front-view-01.png"),
    Car(33, "Nissan Armada", "SUV", "https://www.nissanusa.com/content/dam/nissan/na/us/vehicles/cars/armada/2021/gallery/2021-armada-front-view-01.png"),
    Car(34, "Subaru Ascent", "SUV", "https://www.subaru.com/content/dam/subaru/na/us/vehicles/ascent/2021/gallery/2021-ascent-front-view-01.png"),
)